import type { Metadata } from "next"

import "./globals.css"
import Footer from "./_home/Footer"
import Header from "./_home/Header"

export const metadata: Metadata = {
  title: "Dominic Clerici",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
